/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 22bf41387cac8beec2b7cb2d5454d0a5)
interface __BaseEnv_Env {
  DemoMcpServer: DurableObjectNamespace<import("./src/index").DemoMcpServer>;
  IdentityDO: DurableObjectNamespace<import("./src/index").IdentityDO>;
  WorkspaceDO: DurableObjectNamespace<import("./src/index").WorkspaceDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "DemoMcpServer" | "IdentityDO" | "WorkspaceDO";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
