/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f17581168e4a8eccc7ac99511a1e2140)
interface __BaseEnv_Env {
  DemoMcpServer: DurableObjectNamespace<import("./src/server").DemoMcpServer>;
  IdentityDO: DurableObjectNamespace<import("./src/server").IdentityDO>;
  WorkspaceDO: DurableObjectNamespace<import("./src/server").WorkspaceDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DemoMcpServer" | "IdentityDO" | "WorkspaceDO";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
